export const rent = {
  data: [
    {
      _id: "1",
      img: "https://teja12.kuikr.com/is/a/c/880x425/public/images/apartments/original_img/0n2qu0.gif",
      houseName: "Three Jewels",
      bedrooms: "2",
      city: "Mumbai",
      rentPrice: 25000,
      moveInBy: "09-09-2022",
    },
    {
      _id: "2",
      img: "https://aniportalimages.s3.amazonaws.com/media/details/essel-tower.jpg",
      houseName: "Arihant Galaxy",
      bedrooms: "2",
      city: "Delhi",
      rentPrice: 14000,
      moveInBy: "09-04-2022",
    },
    {
      _id: "3",
      img: "https://teja12.kuikr.com/is/a/c/880x425/gallery_images/original/cf5b6d6f30bfd51.gif",
      houseName: "Gargantua",
      bedrooms: "3",
      city: "Mumbai",
      rentPrice: 30000,
      moveInBy: "10-03-2022",
    },
    {
      _id: "4",
      img: "https://www.commercialproperty.review/wp-content/uploads/2021/02/AWHO-Sandeep-Vihar-Apartments-Ardendale-Bangalore-East.jpeg",
      houseName: "Hogwarts",
      bedrooms: "1",
      city: "Bangalore",
      rentPrice: 12000,
      moveInBy: "08-31-2022",
    },
    {
      _id: "5",
      img: "https://newprojects.99acres.com/projects/unknown/greenland_society/images/elevation.jpeg",
      houseName: "Wakanda",
      bedrooms: "2",
      city: "Pune",
      rentPrice: 10000,
      moveInBy: "09-15-2022",
    },
    {
      _id: "6",
      img: "https://www.orfonline.org/wp-content/uploads/2020/05/Housing-societies-in-a-fix-over-govts-stand-on-COVID19.jpg",
      houseName: "Antilia",
      bedrooms: "3",
      city: "Hyderabad",
      rentPrice: 22000,
      moveInBy: "10-04-2022",
    },
  ],
};
